"""
Django settings for Legalv1 project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import datetime
from logging.handlers import TimedRotatingFileHandler
from celery.schedules import crontab
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load env file from project root reliably
load_dotenv(BASE_DIR / 'legalenv')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 't')

ALLOWED_HOSTS = ['216.48.191.67', 'mamla.ai', 'www.mamla.ai', '127.0.0.1', 'localhost', 'e2e-108-67.ssdcloudindia.net']
# CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
    'x-requested-with',
    'accept',
    'accept-language',
    'x-csrftoken',
]

CORS_ALLOWED_ORIGINS = [
    'https://mamla.ai',
    'https://www.mamla.ai',
    'http://mamla.ai',
    'http://www.mamla.ai',
    'http://localhost:3000',
]

# REST Framework and OpenAPI (Swagger) - schema only when DEBUG=True (see core.views)
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
SPECTACULAR_SETTINGS = {
    'TITLE': 'Mamla.AI API',
    'DESCRIPTION': 'API docs. When DEBUG=True use Authorize with Bearer token or X-Dev-Bypass-Auth: 1 for local testing.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Silence "unable to guess serializer" for @api_view/JsonResponse views (schema still generated for documented endpoints).
    'DISABLE_ERRORS_AND_WARNINGS': True,
    'SECURITY': [{'BearerAuth': []}, {'DevBypassAuth': []}],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http', 'scheme': 'bearer', 'bearerFormat': 'JWT',
                'description': 'Supabase access_token',
            },
            'DevBypassAuth': {
                'type': 'apiKey', 'in': 'header', 'name': 'X-Dev-Bypass-Auth',
                'description': 'Local only (DEBUG=True): set to 1 to skip Supabase auth.',
            },
        },
    },
}

#### for deleteing patterns --> || find . -name "*.pyc" -exec rm -f {} \; ||
#### git config --add --local core.sshCommand 'ssh -i /home/mrityunjoy/work/code/legalGit/adalatai_ssh_key/id_rsa'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'users',
    'calendersetup',
    'create_drafts',
    'utilities',
    'search_facility',
    'ai_draft',
    'whatsapp_module',
    'todaysupdates',
    'core',
    'talkdoc',
    'ecourts_scraper',
    'ecourts_api',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.DevAuthBypassMiddleware',
    'ai_draft.middleware.BypassAuthForTestEndpoints',  
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.UpdateLastActivityMiddleware',
]

# SSL stuffs
SECURE_SSL_REDIRECT = False

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Add CSP Header
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# OpenSearch configuration
OPENSEARCH_HOST = os.getenv('OPENSEARCH_HOST', 'localhost')
OPENSEARCH_PORT = int(os.getenv('OPENSEARCH_PORT', '9200'))
OPENSEARCH_USE_SSL = os.getenv('OPENSEARCH_USE_SSL', '0') == '1'
OPENSEARCH_VERIFY_CERTS = os.getenv('OPENSEARCH_VERIFY_CERTS', '0') == '1'

# ---------------------------------------------------------------------------
# LLM configuration (core.llm_client reads these)
# ---------------------------------------------------------------------------
# Keys
OPENAI_API_KEY     = os.getenv('OPENAI_API_KEY')
OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY')

# Default provider: 'openai' | 'openrouter'
# Override per-deployment without touching code.
LLM_DEFAULT_PROVIDER = os.getenv('LLM_DEFAULT_PROVIDER', 'openai')

# TalkDoc flag (kept for backwards compatibility)
TALKDOC_ENABLE_LLM = os.getenv('TALKDOC_ENABLE_LLM', '1').strip() not in ('0', 'false', 'False')

# Per-app OpenAI model overrides (env takes precedence over llm_client defaults)
OPENAI_AI_DRAFT_MODEL = os.getenv('OPENAI_AI_DRAFT_MODEL', 'gpt-4o-mini')
RAG_CHAT_MODEL        = os.getenv('RAG_CHAT_MODEL',        'gpt-4o')
OPENAI_UTILS_MODEL    = os.getenv('OPENAI_UTILS_MODEL',    'gpt-4o-mini')
OPENAI_CREATE_DRAFTS_MODEL = os.getenv('OPENAI_CREATE_DRAFTS_MODEL', 'gpt-4o')

# Per-app OpenRouter model overrides
OPENROUTER_AI_DRAFT_MODEL         = os.getenv('OPENROUTER_AI_DRAFT_MODEL',         'openai/gpt-4o-mini')
OPENROUTER_TALKDOC_RAG_MODEL      = os.getenv('OPENROUTER_TALKDOC_RAG_MODEL',      'anthropic/claude-3-haiku')
OPENROUTER_TALKDOC_GENERAL_MODEL  = os.getenv('OPENROUTER_TALKDOC_GENERAL_MODEL',  'anthropic/claude-3-haiku')
OPENROUTER_UTILS_MODEL            = os.getenv('OPENROUTER_UTILS_MODEL',            'openai/gpt-4o-mini')
OPENROUTER_CREATE_DRAFTS_MODEL    = os.getenv('OPENROUTER_CREATE_DRAFTS_MODEL',    'openai/gpt-4o')

# Mamla-Brain tier models (used by mamla_brain app — pre-configured)
BRAIN_T1_MODEL = os.getenv('BRAIN_T1_MODEL', 'meta-llama/llama-3.1-8b-instruct')
BRAIN_T2_MODEL = os.getenv('BRAIN_T2_MODEL', 'anthropic/claude-3-haiku')
BRAIN_T3_MODEL = os.getenv('BRAIN_T3_MODEL', 'anthropic/claude-sonnet-4-5')

ROOT_URLCONF = 'Legalv1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Legalv1.wsgi.application'

# settings.py
now_date_str = datetime.strftime(datetime.now().date(),'%d-%m-%Y')
DJANGO_LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', 'INFO' if DEBUG else 'WARNING')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname} -- {asctime} -- {process} -- {funcName} -- {module} -- {lineno} -- {name}] || {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': f'../logs/{now_date_str}_django.log',
            'when': 'midnight',
            'interval': 1,
            'backupCount': 3,
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'] if DEBUG else ['file'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file', 'console'] if DEBUG else ['file'],
            'level': 'ERROR',  # Only log request errors (4xx, 5xx)
            'propagate': False,
        },
        'django.server': {
            'handlers': ['file', 'console'] if DEBUG else ['file'],
            'level': 'ERROR',  # Only log server errors
            'propagate': False,
        },
        'celery': {
            'handlers': ['file', 'console'] if DEBUG else ['file'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
    },
    
}

#frontend url
FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://mamla.ai')

#supabse details
SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_SERVICE_ROLE_KEY = os.getenv('SUPABASE_SERVICE_ROLE_KEY')

# Twilio credentials (optional if using Twilio)
TWILIO_ACCOUNT_SID = 'your_account_sid'
TWILIO_AUTH_TOKEN = 'your_auth_token'
TWILIO_PHONE_NUMBER = 'your_twilio_phone_number'

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# setting up mail
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND')
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# MONGODB
url = f"""mongodb+srv://{os.getenv('MONGO_HOSTNAME')}:{os.getenv('MONGO_PWD')}@userdata.cshoz.mongodb.net/?retryWrites=true&w=majority&appName={os.getenv('MONGO_APPNAME')}"""
MONGO_URI = os.getenv("MONGO_URI",url)


# Celery Configuration
# Redis as the broker for Celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json', 'pickle']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_BEAT_SCHEDULER = 'celery.beat:PersistentScheduler'

CELERY_BEAT_SCHEDULE = {
    'fetch-todays-meetings-daily': {
        'task': 'utilities.tasks.fetch_todays_meetings',
        'schedule': crontab(hour=6, minute=0),  # Every day at 6AM
    },
    # 'cleanup-stuck-documents': task removed (talkdoc.tasks.cleanup_stuck_documents no longer exists)
    'send-hourly-reminders': {
        'task': 'utilities.tasks.send_hourly_reminders',
        'schedule': crontab(minute=0),  # Every hour
    },
    # 'send-quarterly-reminders': {
    #     'task': 'utilities.tasks.send_quarterly_reminders',
    #     'schedule': crontab(minute='*/15'),  # Every 15 minutes
    # },
    'cleanup-previous-day-index-daily': {
        'task': 'utilities.tasks.cleanup_previous_day_index',
        'schedule': crontab(hour=23, minute=59),  # Every day at 23:59
    },
    'send_daily_consolidated_reminders': {
        'task': 'utilities.tasks.send_daily_consolidated_reminders',
        'schedule': crontab(hour=18, minute=0),  # Every day at 6 PM
    },
    'cleanup-inactive-sessions-every-5-minutes': {
        'task': 'users.tasks.cleanup_inactive_sessions',
        'schedule': crontab(minute="*/5"),  # every 5 minutes
    },
    'invalidate-inactive-sessions-every-15-minutes': {
        'task': 'users.tasks.invalidate_inactive_sessions',
        'schedule': crontab(minute="*/15"),  # Every 15 minutes
    },
    'invalidate-all-sessions-weekly': {
        'task': 'users.tasks.invalidate_all_sessions_weekly',
        'schedule': crontab(day_of_week='saturday', hour=0, minute=0),
    },
    # 'invalidate-sessions-weekly-specific-users': {
    #     'task': 'your_app.tasks.invalidate_sessions_weekly_for_specific_users',
    #     'schedule': crontab(day_of_week='saturday', hour=0, minute=0),
    #     'args': [['user_id1', 'user_id2']],  # Replace with actual user IDs
    # },
    'send-todays-service-request-to-paralegals': {
        'task': 'whatsapp_module.tasks.assign_orders_evening',
        'schedule': crontab(hour=21, minute=0),
    },
    'remind-paralegals-of-there-pending-tasks': {
        'task': 'whatsapp_module.tasks.paralegal_reminder_task',
        'schedule': crontab(minute="*/120"),
    },
    'provide-users-there-completed-task-updates': {
        'task': 'whatsapp_module.tasks.notify_clients_end_of_day',
        'schedule': crontab(hour=18, minute=0),
    },
    # Pre-populate default results for eCourts landing pages
    'ecourts-populate-case-defaults-daily': {
        'task': 'ecourts_api.tasks.populate_case_defaults',
        'schedule': crontab(hour=6, minute=30),  # Daily 06:30 UTC
        'options': {'queue': 'ecourts_background'},
    },
    'ecourts-populate-litigant-defaults-daily': {
        'task': 'ecourts_api.tasks.populate_litigant_defaults',
        'schedule': crontab(hour=6, minute=35),  # Daily 06:35 UTC
        'options': {'queue': 'ecourts_background'},
    },
    'ecourts-populate-lawyer-defaults-weekly': {
        'task': 'ecourts_api.tasks.populate_lawyer_defaults',
        'schedule': crontab(day_of_week='monday', hour=6, minute=40),  # Weekly Monday 06:40 UTC
        'options': {'queue': 'ecourts_background'},
    },
    'ecourts-cleanup-expired-cache': {
        'task': 'ecourts_scraper.tasks.cleanup_expired_cache',
        'schedule': crontab(hour=4, minute=0),
        'options': {'queue': 'ecourts_background'},
    },
    'ecourts-health-check-selectors': {
        'task': 'ecourts_scraper.tasks.health_check_selectors',
        'schedule': crontab(hour=3, minute=0),
        'options': {'queue': 'ecourts_background'},
    },
    'ecourts-refresh-subscribed-causelists': {
        'task': 'ecourts_scraper.tasks.refresh_subscribed_causelists',
        'schedule': crontab(hour='6,12,18', minute=30),
        'options': {'queue': 'ecourts_background'},
    },
    'ecourts-refresh-tracked-cases': {
        'task': 'ecourts_scraper.tasks.refresh_tracked_cases',
        'schedule': crontab(hour=2, minute=0),
        'options': {'queue': 'ecourts_background'},
    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = False

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Cache configuration merged from settings/cache.py ---
import redis
from typing import Dict, Any

CACHES: Dict[str, Any] = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://localhost:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,  # seconds
            'SOCKET_TIMEOUT': 5,          # seconds
            'IGNORE_EXCEPTIONS': True,     # Return None on Redis errors
            'PICKLE_VERSION': -1,         # Use highest protocol version
            'CONNECTION_POOL_CLASS': 'redis.ConnectionPool',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 100,
                'retry_on_timeout': True,
                'socket_keepalive': True,
            },
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'SERIALIZER': 'django_redis.serializers.json.JSONSerializer',
        },
        'KEY_PREFIX': 'legalv1',
        'TIMEOUT': 60 * 60 * 24,  # 1 day default timeout
    'KEY_FUNCTION': 'core.cache_utils.make_cache_key',
    },
    # Local memory cache as fallback
    'local': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'legalv1-local',
        'TIMEOUT': 60 * 5,  # 5 minutes
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
            'CULL_FREQUENCY': 3,  # 1/3 of entries removed when max reached
        }
    },
    # File-based cache for development
    'file': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/var/tmp/django_cache',
        'TIMEOUT': 60 * 60 * 24,  # 1 day
        'OPTIONS': {
            'MAX_ENTRIES': 10000,
        }
    }
}

# Session cache configuration
SESSION_CACHE_ALIAS = 'default'
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7 * 2  # 2 weeks
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
SESSION_SAVE_EVERY_REQUEST = True

# Cache timeouts (in seconds)
CACHE_MIDDLEWARE_SECONDS = 60 * 15  # 15 minutes
CACHE_MIDDLEWARE_KEY_PREFIX = 'legalv1'
CACHE_MIDDLEWARE_ALIAS = 'default'

# Redis connection pool settings
REDIS_MAX_CONNECTIONS = int(os.getenv('REDIS_MAX_CONNECTIONS', '100'))
REDIS_CONNECTION_TIMEOUT = int(os.getenv('REDIS_CONNECTION_TIMEOUT', '5'))
REDIS_RETRY_ON_TIMEOUT = os.getenv('REDIS_RETRY_ON_TIMEOUT', 'true').lower() == 'true'

# Cache invalidation settings
CACHE_INVALIDATE_ON_STARTUP = os.getenv('CACHE_INVALIDATE_ON_STARTUP', 'false').lower() == 'true'
CACHE_VERSION = os.getenv('CACHE_VERSION', '1')

# Cache key function
def make_cache_key(key, key_prefix, version):
    """
    Constructs the key used by all other methods.
    """
    return f"{key_prefix}:{version}:{key}"
